<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import MiriCogItemPicker from '@/Components/MiriCogItemPicker.vue';
const props = defineProps({ movementTypes: Array, registerTypes: Array });
let key=0;
const line = () => ({ row_key:++key,item_type:'Major equipment',item_id:'',quantity:1,unit:'',description:'',size_model:'',identifier:'',serial_no:'',mr_reference:'',remarks:'',batch_no:'',location:'' });
const headerFields = [['consignee_name','Consignee name'],['consignee_department','Consignee department'],['from_department','From department / company'],['from_location','From location'],['to_location','To'],['copy_to','Copy to'],['destination','Destination'],['receiver_email','Receiver email (optional)']];
const signers=[{name:'issued_by_name',title:'Issued & Checked By',designation:'issued_designation',date:'issued_date'},{name:'verified_by_name',title:'Verified By: HOD / Supervisor',designation:'verified_designation',date:'verified_date'},{name:'receiver_name',title:'Received By',designation:'receiver_designation',date:'received_date'}];
const form=useForm({movement_type:props.movementTypes[0],document_date:new Date().toLocaleDateString('en-CA'),...Object.fromEntries(headerFields.map(([k])=>[k,''])),...Object.fromEntries(signers.flatMap(s=>[[s.name,''],[s.designation,''],[s.date,'']])),remarks:'',items:[line()]});
const label = type => type === 'Construction' ? 'TEC, Garnet & PPE' : type === 'Major equipment' ? 'Major Equipment (Machinery / Cargo)' : type;
function select(row,item) {
    row.item_id=item?.id || '';
    for (const k of ['description','size_model','identifier','serial_no','mr_reference','unit','batch_no','location']) row[k]=item?.[k] || '';
}
const submit=()=>form.transform(data=>({...data,items:data.items.map(({row_key,batch_no,location,...row})=>row)})).post(route('miri-cogs.store'));
</script>
<template>
<Head title="Create Miri Internal Issue Note" />
<AuthenticatedLayout>
<form class="space-y-6" @submit.prevent="submit">
<header class="rounded-3xl border border-[#d8e7d4] bg-white p-6"><img src="/images/dayang-logo.png" alt="Dayang" class="h-14 w-auto" /><h1 class="mt-4 text-3xl font-bold text-[#234222]">Internal Issue Note</h1><p class="mt-2 text-sm text-slate-500">DE-F-07E · REV.0 · Miri COG</p><p class="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Equipment is reserved as soon as an outbound note is created, including drafts. Record Received backload before issuing it again, or cancel an unfulfilled draft. Stock balances and source locations are not updated.</p></header>
<div v-if="Object.keys(form.errors).length" role="alert" class="rounded-xl bg-red-50 p-4 text-red-700"><p v-for="(error,k) in form.errors" :key="k">{{ error }}</p></div>
<section class="rounded-3xl border bg-white p-6"><h2 class="font-bold text-[#234222]">Document details</h2><div class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label class="text-sm">Movement type<select v-model="form.movement_type" class="mt-2 w-full rounded-xl border-slate-200"><option v-for="type in movementTypes" :key="type">{{ type }}</option></select></label><label class="text-sm">Date<input v-model="form.document_date" type="date" class="mt-2 w-full rounded-xl border-slate-200" required /></label><label v-for="[k,title] in headerFields" :key="k" class="text-sm">{{ title }}<input v-model="form[k]" :type="k==='receiver_email' ? 'email' : 'text'" class="mt-2 w-full rounded-xl border-slate-200" maxlength="255" /></label></div></section>
<section class="rounded-3xl border bg-white p-6"><div class="flex justify-between gap-3"><h2 class="font-bold text-[#234222]">Issue items</h2><button type="button" class="btn bg-[#4f9f4a] text-white" :disabled="form.items.length>=100" @click="form.items.push(line())">Add item</button></div>
<div v-for="(row,i) in form.items" :key="row.row_key" class="mt-5 rounded-2xl border p-4">
<div class="flex justify-between"><h3 class="font-bold">Item {{ i+1 }}</h3><button type="button" class="text-sm text-red-700 disabled:opacity-30" :disabled="form.items.length===1" @click="form.items.splice(i,1)">Remove</button></div>
<div class="mt-3 grid gap-4 md:grid-cols-2"><label class="text-sm">Register<select v-model="row.item_type" class="mt-2 w-full rounded-xl border-slate-200"><option v-for="type in registerTypes" :key="type" :value="type">{{ label(type) }}</option></select></label><label class="text-sm">Search inventory item<MiriCogItemPicker v-model="row.item_id" :type="row.item_type" :movement-type="form.movement_type" @selected="select(row,$event)" /></label></div>
<p class="mt-3 text-xs text-slate-500">Source location: {{ row.location || 'Not recorded' }}<span v-if="row.batch_no"> · Paint batch: {{ row.batch_no }} (included in printed description)</span></p>
<div class="mt-4 grid gap-3 md:grid-cols-3"><label class="text-sm">Quantity<input v-model="row.quantity" type="number" min="0.001" step="0.001" class="mt-2 w-full rounded-xl border-slate-200" /></label><label class="text-sm">Unit<select v-if="row.item_type==='Paint'" v-model="row.unit" class="mt-2 w-full rounded-xl border-slate-200"><option value="">Choose unit</option><option>CAN</option><option>LTR</option></select><input v-else v-model="row.unit" class="mt-2 w-full rounded-xl border-slate-200" maxlength="20" placeholder="Required, e.g. UNIT / PC / TON" /></label><label v-for="[k,title] in [['description','Full description'],['size_model','Size / Model'],['identifier','Tagging / Equipment No.'],['serial_no','Serial No.'],['mr_reference','Material Requisition No.'],['remarks','Remarks']]" :key="k" class="text-sm">{{ title }}<textarea v-if="['mr_reference','remarks'].includes(k)" v-model="row[k]" rows="2" maxlength="1000" class="mt-2 w-full rounded-xl border-slate-200" /><input v-else v-model="row[k]" :disabled="k==='identifier' && row.item_type==='Paint'" maxlength="255" class="mt-2 w-full rounded-xl border-slate-200 disabled:bg-slate-100" /></label></div>
</div></section>
<section class="rounded-3xl border bg-white p-6"><h2 class="font-bold text-[#234222]">Signatory details</h2><p class="mt-2 text-sm text-slate-500">Names are not signatures. Issued/verified boxes remain available for handwritten signing. Digital receiver signing is available after creation; this does not introduce a supervisor approval workflow.</p><div class="mt-5 grid gap-5 lg:grid-cols-3"><div v-for="s in signers" :key="s.name" class="space-y-3 rounded-xl border p-4"><h3 class="text-sm font-bold">{{ s.title }}</h3><label class="block text-sm">Name<input v-model="form[s.name]" :required="s.name==='issued_by_name'" class="mt-1 w-full rounded-lg border-slate-200" /></label><label class="block text-sm">Designation<input v-model="form[s.designation]" class="mt-1 w-full rounded-lg border-slate-200" /></label><label class="block text-sm">Date<input v-model="form[s.date]" type="date" class="mt-1 w-full rounded-lg border-slate-200" /></label></div></div><label class="mt-5 block text-sm">Document remarks<textarea v-model="form.remarks" rows="2" maxlength="1000" class="mt-2 w-full rounded-xl border-slate-200" /></label></section>
<div class="flex gap-3"><button class="btn bg-[#234222] text-white" :disabled="form.processing">Create COG</button><Link :href="route('miri-cogs.index')" class="btn">Cancel</Link></div>
</form>
</AuthenticatedLayout>
</template>
