<?php

use App\Http\Controllers\AssetAssignmentController;
use App\Http\Controllers\PublicAssetCheckinController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\AssetQrCodeController;
use App\Http\Controllers\AssetRepairController;
use App\Http\Controllers\AssistantController;
use App\Http\Controllers\AuditTrailController;
use App\Http\Controllers\BranchContextController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmailActivityLogController;
use App\Http\Controllers\IssueLogController;
use App\Http\Controllers\ItAssetImportController;
use App\Http\Controllers\ItAssetSectionController;
use App\Http\Controllers\ItLicenseController;
use App\Http\Controllers\ItLicenseImportController;
use App\Http\Controllers\ItPeopleController;
use App\Http\Controllers\ItMovementRecordController;
use App\Http\Controllers\KemamanInventoryController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\MajorEquipmentController;
use App\Http\Controllers\MiriLogController;
use App\Http\Controllers\MiriCogController;
use App\Http\Controllers\MiriRentalController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicAssetController;
use App\Http\Controllers\PublicAssetCheckoutController;
use App\Http\Controllers\QuickSearchController;
use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');

Route::get('/asset/{publicToken}', PublicAssetController::class)->name('public.it-assets.show');
Route::get('/asset-checkout/{token}', [PublicAssetCheckoutController::class, 'show'])->name('public.asset-checkout.show');
Route::post('/asset-checkout/{token}/sign', [PublicAssetCheckoutController::class, 'sign'])->name('public.asset-checkout.sign');
Route::get('/asset-checkin/{token}', [PublicAssetCheckinController::class, 'show'])->name('public.asset-checkin.show');
Route::post('/asset-checkin/{token}/sign', [PublicAssetCheckinController::class, 'sign'])->name('public.asset-checkin.sign');
Route::get('/asset-checkin-test-preview', [PublicAssetCheckinController::class, 'testPreview'])->name('settings.asset-checkin-test.preview');
Route::post('/asset-checkin-test-preview/sign', [PublicAssetCheckinController::class, 'testSign'])->name('settings.asset-checkin-test.sign');
Route::get('/asset-checkout-complete', [PublicAssetCheckoutController::class, 'complete'])->name('public.asset-checkout.complete');
Route::get('/asset-checkout-test-preview', [PublicAssetCheckoutController::class, 'testPreview'])->name('settings.asset-checkout-test.preview');
Route::post('/asset-checkout-test-preview/sign', [PublicAssetCheckoutController::class, 'testSign'])->name('settings.asset-checkout-test.sign');

Route::get('/dashboard', DashboardController::class)->middleware(['auth', 'system.access', 'verified'])->name('dashboard');

Route::middleware(['auth', 'system.access'])->group(function () {
    Route::get('/miri-reports/bintulu-yard-consumable', [\App\Http\Controllers\MiriReportsController::class, 'bintuluConsumable'])->name('miri-reports.bintulu-consumable');
    Route::get('/miri-reports/bintulu-yard-consumable/export', [\App\Http\Controllers\MiriReportsController::class, 'exportConsumable'])->name('miri-reports.consumable.export');
    Route::get('/miri-reports', [\App\Http\Controllers\MiriReportsController::class, 'index'])->name('miri-reports.index');
    Route::get('/miri-reports/equipment-rental-summary', [\App\Http\Controllers\MiriReportsController::class, 'rental'])->name('miri-reports.rental');
    Route::get('/miri-reports/equipment-rental-summary/export', [\App\Http\Controllers\MiriReportsController::class, 'exportRental'])->name('miri-reports.rental.export');
    Route::get('/miri-reports/bintulu-yard-cidb-training', [\App\Http\Controllers\MiriReportsController::class, 'bintuluCidb'])->name('miri-reports.bintulu-cidb');
    Route::get('/miri-reports/bintulu-yard-cidb-training/export', [\App\Http\Controllers\MiriReportsController::class, 'exportCidb'])->name('miri-reports.cidb.export');
    Route::get('/miri-reports/bintulu-yard-paint', [\App\Http\Controllers\MiriReportsController::class, 'bintuluPaint'])->name('miri-reports.bintulu-paint');
    Route::get('/miri-reports/paint/export', [\App\Http\Controllers\MiriReportsController::class, 'export'])->name('miri-reports.paint.export');
    Route::patch('/miri-inventory/company-assignment', [\App\Http\Controllers\MiriCompanyController::class, 'assign'])->name('miri-company.assign');
    Route::delete('/miri-register/{register}/{item}', [\App\Http\Controllers\MiriRegisterDeletionController::class, 'destroy'])
        ->whereIn('register', ['major', 'rental', 'construction', 'paint'])->whereNumber('item')->name('miri-register.destroy');
    Route::prefix('miri-paint')->name('paint.')->controller(\App\Http\Controllers\MiriPaintController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('/import', 'importPage')->name('import');
        Route::post('/import/preview', 'preview')->name('import.preview');
        Route::post('/import', 'queueImport')->name('import.store');
        Route::get('/import/{task}', 'importStatus')->whereUuid('task')->name('import.status');
        Route::get('/{paint}', 'show')->whereNumber('paint')->name('show');
        Route::get('/{paint}/edit', 'edit')->whereNumber('paint')->name('edit');
        Route::patch('/{paint}', 'update')->whereNumber('paint')->name('update');
    });
    Route::prefix('miri-construction')->name('construction.')->controller(\App\Http\Controllers\MiriConstructionController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('/import', 'importPage')->name('import');
        Route::post('/import/preview', 'preview')->name('import.preview');
        Route::post('/import', 'queueImport')->name('import.store');
        Route::get('/import/{task}', 'importStatus')->whereUuid('task')->name('import.status');
        Route::get('/{construction}', 'show')->whereNumber('construction')->name('show');
        Route::get('/{construction}/edit', 'edit')->whereNumber('construction')->name('edit');
        Route::patch('/{construction}', 'update')->whereNumber('construction')->name('update');
        Route::post('/{construction}/stock', 'stock')->whereNumber('construction')->name('stock');
        Route::get('/{construction}/attachments/{slot}', 'attachment')->whereNumber('construction')->name('attachment');
    });
    Route::patch('/active-branch', [BranchContextController::class, 'update'])->name('branches.activate');
    Route::patch('/it-assets/bulk-update', [AssetController::class, 'bulkUpdate'])->name('it-assets.bulk-update');
    Route::get('/it-assets/bulk-edit', [AssetController::class, 'bulkEdit'])->name('it-assets.bulk-edit');
    Route::resource('it-assets', AssetController::class)->parameters(['it-assets' => 'asset'])->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::resource('it-licenses', ItLicenseController::class)->parameters(['it-licenses' => 'it_license'])->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::post('/it-assets/{asset}/checkout', [AssetAssignmentController::class, 'store'])->name('it-assets.checkout');
    Route::post('/it-assets/{asset}/checkout/resend', [AssetAssignmentController::class, 'resend'])->name('it-assets.checkout.resend');
    Route::post('/it-assets/{asset}/checkout/reopen', [AssetAssignmentController::class, 'reopen'])->name('it-assets.checkout.reopen');
    Route::post('/it-asset-assignments/{assignment}/check-in/reopen', [AssetAssignmentController::class, 'reopenCheckin'])->name('it-assets.checkin.reopen');
    Route::post('/it-asset-assignments/{assignment}/check-in/resend', [AssetAssignmentController::class, 'resendCheckin'])->name('it-assets.checkin.resend');
    Route::post('/it-movement-records/{document}/check-in/reset', [AssetAssignmentController::class, 'resetCheckinDocument'])->name('it-assets.checkin.reset-document');
    Route::patch('/it-assets/{asset}/check-in', [AssetAssignmentController::class, 'destroy'])->name('it-assets.check-in');
    Route::post('/it-asset-repairs', [AssetRepairController::class, 'store'])->name('it-assets.repairs.store');
    Route::patch('/it-assets/{asset}/return-from-repair', [AssetRepairController::class, 'returnFromRepair'])->name('it-assets.repairs.return');
    Route::get('/it-assets/{asset}/qr-code', [AssetQrCodeController::class, 'show'])->name('it-assets.qr-code.show');
    Route::post('/it-assets/{asset}/qr-code', [AssetQrCodeController::class, 'store'])->name('it-assets.qr-code.store');
    Route::post('/it-assets/{asset}/qr-code/regenerate', [AssetQrCodeController::class, 'update'])->name('it-assets.qr-code.regenerate');
    Route::post('/it-asset-qr-codes/generate-all', [AssetQrCodeController::class, 'storeAll'])->name('it-assets.qr-codes.store-all');
    Route::get('/it-assets-import', [ItAssetImportController::class, 'create'])->name('it-assets.import.create');
    Route::post('/it-assets-import/preview', [ItAssetImportController::class, 'preview'])->name('it-assets.import.preview');
    Route::post('/it-assets-import', [ItAssetImportController::class, 'store'])->name('it-assets.import.store');
    Route::get('/it-licenses-import', [ItLicenseImportController::class, 'create'])->name('it-licenses.import.create');
    Route::post('/it-licenses-import/preview', [ItLicenseImportController::class, 'preview'])->name('it-licenses.import.preview');
    Route::post('/it-licenses-import', [ItLicenseImportController::class, 'store'])->name('it-licenses.import.store');
    Route::get('/it-dashboard', [ItAssetSectionController::class, 'dashboard'])->name('it-assets.dashboard');
    Route::get('/it-people', [ItPeopleController::class, 'index'])->name('it-people.index');
    Route::get('/it-people/{person}', [ItPeopleController::class, 'show'])->name('it-people.show');
    Route::post('/it-people/{person}/link-ad', [ItPeopleController::class, 'linkAdUser'])->name('it-people.link-ad');
    Route::get('/it-movement-records', [ItMovementRecordController::class, 'index'])->name('it-movement-records.index');
    Route::get('/it-movement-records/{document}/download', [ItMovementRecordController::class, 'download'])->name('it-movement-records.download');
    Route::get('/it-asset-repairs', [ItAssetSectionController::class, 'repairs'])->name('it-assets.repairs');
    Route::get('/quick-search', QuickSearchController::class)->name('quick-search');
    Route::get('/assistant', [AssistantController::class, 'index'])->name('assistant.index');
    Route::post('/assistant/query', [AssistantController::class, 'query'])->name('assistant.query');
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('/settings/test-supervisor-email', [SettingsController::class, 'sendSupervisorTestEmail'])->name('settings.test-supervisor-email');
    Route::post('/settings/import-ldap-users', [SettingsController::class, 'importLdapUsers'])->name('settings.import-ldap-users');
    Route::post('/settings/test-asset-checkout-email', [SettingsController::class, 'sendAssetCheckoutTestEmail'])->name('settings.test-asset-checkout-email');
    Route::get('/settings/preview-asset-checkout-pdf', [PublicAssetCheckoutController::class, 'previewPdf'])->name('settings.preview-asset-checkout-pdf');
    Route::get('/settings/preview-asset-checkin-pdf', [PublicAssetCheckinController::class, 'previewPdf'])->name('settings.preview-asset-checkin-pdf');
    Route::post('/settings/test-asset-checkin-email', [SettingsController::class, 'sendAssetCheckinTestEmail'])->name('settings.test-asset-checkin-email');
    Route::patch('/settings/users/{user}/access', [SettingsController::class, 'updateUserAccess'])->name('settings.users.update');
    Route::get('/settings/issue-logs', [IssueLogController::class, 'index'])->name('settings.issue-logs.index');
    Route::get('/settings/email-activity', [EmailActivityLogController::class, 'index'])->name('settings.email-activity.index');
    Route::get('/settings/email-activity/{emailActivityLog}', [EmailActivityLogController::class, 'show'])->name('settings.email-activity.show');
    Route::get('/audit-trail', [AuditTrailController::class, 'index'])->name('audit-trail.index');
    Route::get('/kemaman-equipment-dashboard', [KemamanInventoryController::class, 'dashboard'])->name('kemaman-inventory.dashboard');
    Route::get('/kemaman-inventory', [KemamanInventoryController::class, 'index'])->name('kemaman-inventory.index');
    Route::post('/kemaman-inventory', [KemamanInventoryController::class, 'store'])->name('kemaman-inventory.store');
    Route::patch('/kemaman-inventory/{item}', [KemamanInventoryController::class, 'update'])->name('kemaman-inventory.update');
    Route::delete('/kemaman-inventory/{item}', [KemamanInventoryController::class, 'destroy'])->name('kemaman-inventory.destroy');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('categories', CategoryController::class)->only(['index', 'store', 'update']);
    Route::post('/miri-inventory/categories', [CategoryController::class, 'storeMiri'])->name('miri-categories.store');
    Route::patch('/miri-inventory/categories/{category}', [CategoryController::class, 'updateMiri'])->name('miri-categories.update');
    Route::delete('/miri-inventory/categories/{category}', [CategoryController::class, 'destroyMiri'])->name('miri-categories.destroy');
    Route::get('/miri-rental', [MiriRentalController::class, 'index'])->name('miri-rental.index');
    Route::get('/miri-rental/create', [MiriRentalController::class, 'create'])->name('miri-rental.create');
    Route::post('/miri-rental', [MiriRentalController::class, 'store'])->name('miri-rental.store');
    Route::get('/miri-rental/import', [MiriRentalController::class, 'import'])->name('miri-rental.import');
    Route::post('/miri-rental/import', [MiriRentalController::class, 'storeImport'])->name('miri-rental.import.store');
    Route::get('/miri-rental/{rental}', [MiriRentalController::class, 'show'])->name('miri-rental.show');
    Route::get('/miri-rental/{rental}/pdf', [MiriRentalController::class, 'pdf'])->name('miri-rental.pdf');
    Route::get('/miri-rental/{rental}/edit', [MiriRentalController::class, 'edit'])->name('miri-rental.edit');
    Route::patch('/miri-rental/{rental}', [MiriRentalController::class, 'update'])->name('miri-rental.update');
    Route::resource('locations', LocationController::class)->only(['index', 'store', 'update']);
    Route::get('/miri-inventory', [MajorEquipmentController::class, 'index'])->name('major-equipment.index');
    Route::get('/miri-inventory/dashboard', [MajorEquipmentController::class, 'dashboard'])->name('major-equipment.dashboard');
    Route::get('/miri-inventory/import-status/{task}', [MajorEquipmentController::class, 'importStatus'])->whereUuid('task')->name('major-equipment.import.status');
    Route::get('/miri-inventory/movement', [MajorEquipmentController::class, 'movement'])->name('major-equipment.movement');
    Route::get('/miri-inventory/log', [MiriLogController::class, 'index'])->name('major-equipment.log');
    Route::get('/miri-cogs', [MiriCogController::class, 'index'])->name('miri-cogs.index');
    Route::get('/miri-cogs/items', [MiriCogController::class, 'items'])->name('miri-cogs.items');
    Route::get('/miri-cogs/create', [MiriCogController::class, 'create'])->name('miri-cogs.create');
    Route::post('/miri-cogs', [MiriCogController::class, 'store'])->name('miri-cogs.store');
    Route::post('/miri-cogs/{cog}/cancel', [MiriCogController::class, 'cancel'])->name('miri-cogs.cancel');
    Route::post('/miri-cogs/{cog}/sign', [MiriCogController::class, 'sign'])->name('miri-cogs.sign');
    Route::get('/miri-cogs/{cog}/edit', [MiriCogController::class, 'edit'])->name('miri-cogs.edit');
    Route::patch('/miri-cogs/{cog}', [MiriCogController::class, 'update'])->name('miri-cogs.update');
    Route::post('/miri-cogs/{cog}/confirm-stock', [MiriCogController::class, 'confirmStock'])->name('miri-cogs.confirm-stock');
    Route::get('/miri-cogs/{cog}/pdf', [MiriCogController::class, 'pdf'])->name('miri-cogs.pdf');
    Route::get('/miri-cogs/{cog}', [MiriCogController::class, 'show'])->name('miri-cogs.show');
    Route::get('/miri-inventory/create', [MajorEquipmentController::class, 'create'])->name('major-equipment.create');
    Route::post('/miri-inventory', [MajorEquipmentController::class, 'store'])->name('major-equipment.store');
    Route::get('/miri-inventory/import', [MajorEquipmentController::class, 'import'])->name('major-equipment.import');
    Route::post('/miri-inventory/import/preview', [MajorEquipmentController::class, 'previewImport'])->name('major-equipment.import.preview');
    Route::post('/miri-inventory/import', [MajorEquipmentController::class, 'storeImport'])->name('major-equipment.import.store');
    Route::get('/miri-inventory/{equipment}', [MajorEquipmentController::class, 'show'])->name('major-equipment.show');
    Route::get('/miri-inventory/{equipment}/certificates/{certificate}/image', [\App\Http\Controllers\MiriCertificateImageController::class, 'show'])->whereNumber('certificate')->name('major-equipment.certificates.image');
    Route::get('/miri-inventory/{equipment}/pdf', [MajorEquipmentController::class, 'pdf'])->name('major-equipment.pdf');
    Route::get('/miri-inventory/{equipment}/edit', [MajorEquipmentController::class, 'edit'])->name('major-equipment.edit');
    Route::patch('/miri-inventory/{equipment}', [MajorEquipmentController::class, 'update'])->name('major-equipment.update');
});

require __DIR__.'/auth.php';
