<script setup>
import { computed } from 'vue';
import { Link } from '@inertiajs/vue3';

const props = defineProps({ dashboard: { type: Object, required: true } });
const total = computed(() => Number(props.dashboard.summary?.total ?? 0));
const percent = (value) => total.value ? Math.round((Number(value) / total.value) * 100) : 0;
const max = (items) => Math.max(...items.map((item) => Number(item.value)), 1);
const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '-';
const dueLabel = (days) => days === 0 ? 'Due today' : `${days} days left`;
</script>

<template>
    <section class="rental-dashboard space-y-6">
        <header class="relative isolate overflow-hidden rounded-[1.75rem] bg-[linear-gradient(120deg,#064e3b_0%,#0f766e_58%,#155e75_100%)] px-5 py-6 text-white shadow-[0_24px_70px_rgba(6,78,59,.22)] sm:px-8 sm:py-8 lg:px-10"><div class="pointer-events-none absolute -right-16 -top-24 h-72 w-72 rounded-full bg-cyan-300/20 blur-2xl"/><div class="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p class="text-xs font-semibold uppercase tracking-[.24em] text-emerald-200">Miri Inventory</p><h1 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Rental dashboard</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-white/70 sm:text-base">Track hired equipment, return dates, locations, suppliers, and rental movement at a glance.</p></div><Link :href="route('miri-rental.index')" class="inline-flex w-fit rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-emerald-900 shadow-sm hover:bg-emerald-50">Open rental register</Link></div></header>

        <div class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6 lg:gap-4"><div v-for="card in [{label:'Total rentals',value:dashboard.summary.total,color:'bg-slate-800'},{label:'On hire',value:dashboard.summary.on_hire,color:'bg-emerald-500'},{label:'Issued',value:dashboard.summary.issued,color:'bg-blue-500'},{label:'Backloaded',value:dashboard.summary.backload,color:'bg-violet-500'},{label:'Due in 30 days',value:dashboard.summary.due_30_days,color:'bg-amber-500'},{label:'Overdue',value:dashboard.summary.overdue,color:'bg-rose-500'}]" :key="card.label" class="relative overflow-hidden rounded-2xl border border-[#d8e7d4] bg-white p-4 shadow-[0_8px_28px_rgba(39,89,45,.06)]"><div class="absolute inset-x-0 top-0 h-1" :class="card.color"/><p class="text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-500">{{ card.label }}</p><p class="mt-2 text-2xl font-black text-slate-800">{{ card.value }}</p></div></div>

        <div class="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:gap-5"><article class="rounded-[1.5rem] border border-[#d9e8d5] bg-white p-5 shadow-[0_12px_35px_rgba(39,89,45,.07)] sm:p-6 lg:col-span-5"><div class="flex items-start justify-between gap-4"><div><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-blue-500">Rental health</p><h2 class="mt-1 text-xl font-black tracking-tight text-slate-800">Status overview</h2></div><span class="text-right text-xs text-slate-400"><strong class="block text-lg text-slate-700">{{ total }}</strong>rentals</span></div><div class="mt-6 space-y-3"><div v-for="item in dashboard.status" :key="item.label" class="flex items-center gap-3"><span class="h-2.5 w-2.5 rounded-full" :class="item.label === 'Overdue' ? 'bg-rose-500' : item.label === 'Issued' ? 'bg-blue-500' : item.label === 'Received Backload' ? 'bg-violet-500' : 'bg-emerald-500'"/><span class="min-w-0 flex-1 text-sm font-semibold text-slate-600">{{ item.label }}</span><div class="hidden h-2 w-24 overflow-hidden rounded-full bg-slate-100 sm:block"><span class="block h-full rounded-full bg-emerald-500" :style="{ width: `${percent(item.value)}%` }"/></div><strong class="w-8 text-right text-sm text-slate-800">{{ item.value }}</strong></div></div></article><article class="rounded-[1.5rem] border border-[#d9e8d5] bg-white p-5 shadow-[0_12px_35px_rgba(39,89,45,.07)] sm:p-6 lg:col-span-7"><div><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-amber-500">Return planning</p><h2 class="mt-1 text-xl font-black tracking-tight text-slate-800">Rental due dates</h2><p class="mt-1 text-xs text-slate-500">Expected returns by month, based on recorded rental due dates.</p></div><div class="mt-7 flex h-36 items-end gap-3 sm:gap-5"><div v-for="month in dashboard.dueTimeline" :key="month.full_label" class="flex min-w-0 flex-1 flex-col items-center gap-2"><strong class="text-xs text-slate-700">{{ month.value || '' }}</strong><div class="flex h-24 w-full items-end rounded-t-lg bg-slate-50"><span class="block w-full rounded-t-lg bg-[linear-gradient(180deg,#f59e0b,#f97316)]" :style="{ height: `${month.value ? Math.max((month.value / max(dashboard.dueTimeline)) * 100, 8) : 3}%` }"/></div><span class="text-[11px] font-bold text-slate-400">{{ month.label }}</span></div></div></article></div>

        <div class="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:gap-5"><article class="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-[0_12px_35px_rgba(15,23,42,.06)] sm:p-6 lg:col-span-5"><div><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-violet-500">Deployment footprint</p><h2 class="mt-1 text-xl font-black tracking-tight text-slate-800">Rental locations</h2></div><div class="mt-6 space-y-4"><div v-for="item in dashboard.locations" :key="item.label"><div class="mb-1 flex justify-between gap-3 text-sm"><span class="truncate font-semibold text-slate-600">{{ item.label }}</span><strong class="text-slate-800">{{ item.value }}</strong></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><span class="block h-full rounded-full bg-[linear-gradient(90deg,#8b5cf6,#3b82f6)]" :style="{ width: `${(item.value / max(dashboard.locations)) * 100}%` }"/></div></div><p v-if="!dashboard.locations.length" class="text-sm text-slate-500">No rental locations recorded.</p></div></article><article class="rounded-[1.5rem] border border-[#d9e8d5] bg-white p-5 shadow-[0_12px_35px_rgba(39,89,45,.07)] sm:p-6 lg:col-span-7"><div><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-emerald-600">Action queue</p><h2 class="mt-1 text-xl font-black tracking-tight text-slate-800">Upcoming rental returns</h2></div><div class="mt-5 space-y-2"><Link v-for="item in dashboard.upcoming" :key="item.id" :href="route('miri-rental.show', item.id)" class="flex items-center gap-3 rounded-xl bg-[#f7fbf5] px-4 py-3 hover:bg-[#eef8ea]"><span class="min-w-0 flex-1"><strong class="block truncate text-sm text-[#234222]">{{ item.identifier || 'Unidentified' }} · {{ item.description || 'Unnamed rental' }}</strong><small class="block truncate text-xs text-slate-500">{{ item.location || 'Location not recorded' }} · {{ item.supplier || 'Supplier not recorded' }}</small></span><span class="shrink-0 text-right"><strong class="block text-xs" :class="item.days_remaining <= 30 ? 'text-amber-600' : 'text-emerald-600'">{{ dueLabel(item.days_remaining) }}</strong><small class="text-[11px] text-slate-400">{{ formatDate(item.due_date) }}</small></span></Link><p v-if="!dashboard.upcoming.length" class="text-sm text-slate-500">No upcoming rental due dates recorded.</p></div></article></div>

        <article class="rounded-[1.5rem] border border-[#d9e8d5] bg-white p-5 shadow-[0_12px_35px_rgba(39,89,45,.07)] sm:p-6"><div class="flex items-start justify-between gap-4"><div><p class="text-[10px] font-extrabold uppercase tracking-[.22em] text-cyan-600">Latest activity</p><h2 class="mt-1 text-xl font-black tracking-tight text-slate-800">Recently updated rentals</h2></div><Link :href="route('miri-rental.index')" class="text-sm font-bold text-emerald-700 hover:underline">View register →</Link></div><div class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Link v-for="item in dashboard.recent" :key="item.id" :href="route('miri-rental.show', item.id)" class="rounded-xl bg-[#f7fbf5] px-4 py-3 hover:bg-[#eef8ea]"><p class="truncate font-semibold text-[#234222]">{{ item.identifier || 'Unidentified' }}</p><p class="mt-1 truncate text-xs text-slate-500">{{ item.description || '-' }}</p><p class="mt-2 text-[11px] text-slate-400">{{ item.status || 'Not stated' }} · {{ item.updated_at }}</p></Link><p v-if="!dashboard.recent.length" class="text-sm text-slate-500">No rental records imported yet.</p></div></article>
    </section>
</template>

<style scoped>
.rental-dashboard { font-family: "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-feature-settings: "kern" 1, "tnum" 1; }
</style>
